### ISSUE TITLE
Error when _R_CHECK_LENGTH_1_LOGIC2_=true

### ISSUE THREAD

**Issue by gadenbuie** [sjp/selectr#11]
These lines in `tokenize()` break when `_R_CHECK_LENGTH_1_LOGIC2_=true` in R 3.6. 

https://github.com/sjp/selectr/blob/7bd1b0f834fc7eaa1b6dde749a1b847884663dc0/R/parser.R#L684

I'm sorry I don't have a direct reprex, but I ran into this problem while using `cliapp` and I included a small reprex there: https://github.com/r-lib/cliapp/issues/14

**Comment by HenrikBengtsson** [comment]
I came here after having spent time troubleshooting this bug first thinking it was a bug in {cliapp}. I'm pretty sure others repeat this too. Can I encourage you to submit the fixed version of {selectr} to CRAN?

In the bigger picture, this will also help R and CRAN to be eventually to enable `_R_CHECK_LENGTH_1_LOGIC2_=true` by default. Getting to that stage in R will improve the overall quality and trust in R. The more packages that are fixed the more likely it is that more people enables these checks (without having to worry about their workflow getting interrupted).  Hopefully they'll be able to do this for R 4.0.0 (April 2020) but it needs lots of help from the community. Thxs.

**Comment by sjp** [comment]
Thanks @HenrikBengtsson for the suggestion. I've submitted a new version to CRAN. It should be available soon.

Good points regarding `_R_CHECK_LENGTH_1_LOGIC2`, all of which I agree with. Looking forward to R 4.0.0!
